import argparse

from profiler.runner import run_target
from profiler.analyzer import analyze_trace
from profiler.display import render_analysis
from profiler.installer import install_lib
from profiler.exporter import export_html

def main():
    parser = argparse.ArgumentParser(description="MemTracker - Memory Profiling Tool")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    run_parser = subparsers.add_parser("run", help="Run the target program with memory profiling, use LD_PRELOAD to load the profiler shared library.")
    run_parser.add_argument("target", help="The target program to run")

    analyze_parser = subparsers.add_parser("analyze", help="Analyze the trace file and display memory profiling statistics")
    analyze_parser.add_argument("trace_file", help="Path to the trace file generated by the profiler")

    export_parser = subparsers.add_parser("export", help="Export the trace into a HTML file to have a more graphic view of analysis")
    export_parser.add_argument("trace_file", help="Path to the trace file generated by the profiler")
    export_parser.add_argument("html_output", help="Path to the HTML file generated by the exporter")

    args = parser.parse_args()

    if args.command == "run":
        install_done = install_lib()

        if (install_done):
            run_target(args.target)
        else:
            print(f"Shutting down the program !") 
            exit(0)

    elif args.command == "analyze":
        stats = analyze_trace(args.trace_file)
        render_analysis(stats)
    elif args.command == "export":
        stats = analyze_trace(args.trace_file)
        export_html(stats, args.html_output)
    else: 
        parser.print_help()

if __name__ == "__main__":
    main()